[project]
name = "image-resizer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.5.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]
